version: "3"
services:
  hotels-reservation-db:
    build:
      context: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql

  loyalty-service:
    build:
      context: v2
      args:
        PROJECT: loyaltyService
    restart: unless-stopped
    ports:
      - 8050:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotels-reservation-db:5432/loyalties
      - SPRING_DATASOURCE_USERNAME=loyalty
      - SPRING_DATASOURCE_PASSWORD=loyalty
    depends_on:
      - hotels-reservation-db

  payment-service:
    build:
      context: v2
      args:
        PROJECT: paymentService
    restart: unless-stopped
    ports:
      - 8060:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotels-reservation-db:5432/payments
      - SPRING_DATASOURCE_USERNAME=payment
      - SPRING_DATASOURCE_PASSWORD=payment
    depends_on:
      - hotels-reservation-db

  reservation-service:
    build:
      context: v2
      args:
        PROJECT: reservationService
    restart: unless-stopped
    ports:
      - 8060:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotels-reservation-db:5432/reservations
      - SPRING_DATASOURCE_USERNAME=reservation
      - SPRING_DATASOURCE_PASSWORD=reservation
    depends_on:
      - hotels-reservation-db


# TODO добавить сервисы

volumes:
  db-data:
