server:
  servlet:
    context-path: /api/v1
    application-display-name: gateway
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      resolve-lazily: true
custom:
  services:
    loyalty: http://localhost:8050/api/v1/loyalties
    payment: http://localhost:8060/api/v1/payments
    reservation: http://localhost:8070/api/v1
