server:
  servlet:
    application-display-name: gateway
  forward-headers-strategy: framework
spring:
  servlet:
    multipart:
      resolve-lazily: true
  cloud:
    openfeign:
      circuitbreaker:
        group:
          enabled: true
        enabled: true
        alphanumeric-ids:
          enabled: true
custom:
  services:
    loyalty: http://localhost:8050/api/v1/loyalties
    payment: http://localhost:8060/api/v1/payments
    reservation: http://localhost:8070/api/v1


resilience4j:
  timelimiter:
    instances:
      LoyaltyClient:
        timeout-duration: 10s
  circuitbreaker:
    instances:
      LoyaltyClient:
        minimumNumberOfCalls: 10

  retry:
    instances:
      LoyaltyClient:
        retryExceptions:
          - java.lang.Throwable
        max-attempts: 10
        wait-duration: 1s

rabbitmq:
  host: localhost
  port: 5672
  queues:
    requests: "requests"
  exchanges:
    requests: "requests"
